### ISSUE TITLE
Dart command keep crashing on non-latin environment if google analytics is not available

### ISSUE THREAD

**Issue by ctrysbita** [dart-lang/tools#131]
The dart command keep crashing when
- google analytics is not available
- the exception contains non-latin letters

```powershell
PS D:\> dart --disable-analytics
An unexpected error was encountered by the Dart CLI.
Please file an issue at https://github.com/dart-lang/sdk/issues/new with the following details:

Invocation: 'dart --disable-analytics'
Exception: 'Invalid argument (string): Contains invalid characters.: "ClientException with SocketException: 远程计算机拒绝网络连接。\r\n (OS Error: 远程计算机拒绝网络连接。\r\n, errno = 1225), address = www.google-analytics.com, port = 1413, uri=https://www.google-analytics.com/mp/collect?measurement_id=G-04BXPVBCWJ&api_secret=Ka1jc8tZSzWc_GXMWHfPHA"'
Stack Trace:
#0      _UnicodeSubsetEncoder.convert (dart:convert/ascii.dart:85:9)
#1      Latin1Codec.encode (dart:convert/latin1.dart:40:46)
#2      new Response (package:http/src/response.dart:37:49)
#3      GAClient.sendData (package:unified_analytics/src/ga_client.dart:73:47)
<asynchronous suspension>
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:180:7)
<asynchronous suspension>
#5      runDartdev (package:dartdev/dartdev.dart:59:16)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

**Comment by devoncarew** [comment]
cc @eliasyishak

**Comment by eliasyishak** [comment]
Thank you for filing and fixing the issue!
